### ISSUE TITLE
Concurrency issues in CI

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#1412]
### Description

We're seeing concurrency issues in CI where PRs are cancelling each others' jobs.

### Steps to reproduce

This most commonly occurs when dependabot opens multiple simultaneous PRs.

The issue is that `github.ref` isn't specific enough and returns `main` for PRs. We can make this more robust.

See https://docs.github.com/en/actions/learn-github-actions/contexts for details.

### Version

0.5.0.dev0 (06f91f7fbba684d976d4df6c4856e4221a17af36)

**Comment by adamjstewart** [comment]
For reference, here are the `github` contexts for the following events:

* [pull_request.txt](https://github.com/microsoft/torchgeo/files/11776746/pull_request.txt)
* [push.txt](https://github.com/microsoft/torchgeo/files/11776756/push.txt)

**Comment by adamjstewart** [comment]
> The issue is that `github.ref` isn't specific enough and returns `main` for PRs.

It seems like `github.ref` is specific enough for both:

* pull_request: "refs/pull/1422/merge"
* push: "refs/heads/main"

I no longer know why this is occurring.

**Comment by adamjstewart** [comment]
[This](https://github.com/github/docs/blob/v1.0.1/.github/workflows/test.yml#L18) looks promising:

```yaml
# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
```

I would still like to better understand why the issue is occuring though.
