### ISSUE TITLE
Wandb logger conflict using LightningCLI

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#1621]
### Description

When using the Wandb logger with Lightning CLI a `config.yaml` will be written to the working dir and cause subsequent runs to error and fail until this file is deleted. This is due to https://github.com/Lightning-AI/lightning/issues/17168

The workaround is to pass `LightningCLI(save_config_kwargs={"overwrite": True})`  in `torchgeo.main.py`

### Steps to reproduce

In lightning config:

```yaml
trainer:
  min_epochs: 10
  max_epochs: 50
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: my-proj
```

Will result in 
```
RuntimeError: SaveConfigCallback expected ./config.yaml to NOT exist. Aborting to avoid overwriting results of a previous run. You can delete the previous config file, set `LightningCLI(save_config_callback=None)` to disable config saving, or set `LightningCLI(save_config_kwargs={"overwrite": True})` to overwrite the config file.
```

### Version

0.5.0
